base:
    seed: &seed 0
model:
    type: model_type
    path: model path
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    n_samples: 128
    path: calib data path
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
    inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 64
        # calib_algo: mse
        # mse_b_num: 2
    special:
        actorder: False
        static_groups: False
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
    quant_out: True
save:
    save_fake: False
    save_path: ./save_gptq_w4a16
